language: generic
dist: trusty
sudo: required
install:
  - sudo apt install texlive-latex-recommended
  - sudo apt install texlive-fonts-recommended
script:
  - ptex2pdf -l pasj.tex
  - mkdir public
  - mv pasj.pdf public
deploy:
deploy:
  provider: pages
  local-dir: public
  target-branch: gh-pages
  github-token: $GITHUB_TOKEN
  skip-cleanup: true
  keep-history: true
  on:
    branch: master
