language: generic
dist: trusty
addons:
  apt:
    packages:
      - texlive-lang-english
      - texlive-latex-recommended
      - texlive-fonts-recommended
script:
  - latexmk
  - mkdir public
  - mv pasj.pdf public
deploy:
  provider: pages
  local-dir: public
  target-branch: gh-pages
  github-token: $GITHUB_TOKEN
  skip-cleanup: true
  keep-history: true
  on:
    branch: master
