language: generic
dist: trusty
addons:
  apt:
    packages:
      - qpdf
      - texlive-lang-cjk
      - texlive-latex-recommended
      - texlive-fonts-recommended
script:
  - ptex2pdf -l pasj.tex
  - mkdir public
  - qpdf --encrypt $PDF_PW $PDF_PW 256 public/pasj.pdf
deploy:
  provider: pages
  local-dir: public
  target-branch: gh-pages
  github-token: $GITHUB_TOKEN
  skip-cleanup: true
  keep-history: true
  on:
    branch: master
