name: Main

on:
  push:
    branches:
      - master

jobs:
  job:
    runs-on: ubuntu-latest
    env:
      ARTICLE: pasj
      PUBLISH_DIR: public
      PUBLISH_BRANCH: gh-pages
      GH_PAGES_URL: https://astropenguin.github.io/latex-ci-demo
      PDF_PW: ${{ secrets.PDF_PW }}
      PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v1
      - name: Install packages
        run: |
          sudo apt install qpdf
          sudo apt install texlive-lang-cjk
          sudo apt install texlive-latex-recommended
          sudo apt install texlive-fonts-recommended
      - name: Build LaTeX
        run: |
          ptex2pdf -l $ARTICLE.tex
      - name: Encrypt PDF
        run: |
          ENCRYPTED=$ARTICLE-$(git rev-parse --short HEAD)
          echo ::set-env name=ENCRYPTED::$ENCRYPTED
          qpdf --encrypt "$PDF_PW" "$PDF_PW" 256 -- $ARTICLE.pdf $ENCRYPTED.pdf
      - name: Make products
        run: |
          mkdir $PUBLISH_DIR
          touch $PUBLISH_DIR/.nojekyll
          mv $ENCRYPTED.pdf $PUBLISH_DIR
      - name: Deploy products
        uses: peaceiris/actions-gh-pages@v2.6.0-rc0
        with:
          forceOrphan: true
      - name: Notify Slack
        run: |
          PAYLOAD="payload={\"text\": \"$GH_PAGES_URL/$ENCRYPTED.pdf\"}"
          curl -X POST --data-urlencode "$PAYLOAD" $SLACK_WEBHOOK_URL
