name: Main

on:
  push:
    branches:
      - master

jobs:
  job:
    runs-on: ubuntu-latest
    env:
      ARTICLE: pasj
      PUBLISH_DIR: public
      PUBLISH_BRANCH: gh-pages
      PDF_PW: ${{ secrets.PDF_PW }}
      PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      GH_PAGES_URL: https://astropenguin.github.io/latex-ci-demo
    steps:
      - uses: actions/checkout@v1
      - name: Install packages
        run: |
          sudo apt install qpdf
          sudo apt install texlive-lang-cjk
          sudo apt install texlive-latex-recommended
          sudo apt install texlive-fonts-recommended
      - name: Build LaTeX document
        run: |
          ptex2pdf -l $ARTICLE.tex
      - name: Encrypt PDF
        run: |
          ENCRYPTED=$ARTICLE-$(git rev-parse --short HEAD)
          echo ::set-output name=url::${GH_PAGES_URL}/$ENCRYPTED.pdf
          mkdir $PUBLISH_DIR
          qpdf --encrypt $PDF_PW $PDF_PW 256 -- $ARTICLE.pdf $PUBLISH_DIR/$ENCRYPTED.pdf
      - name: Deploy PDF
        uses: peaceiris/actions-gh-pages@v2.5.0
      - name: Notify Slack
        uses: Ilshidur/action-slack@1.6.2
        with:
          args: URL is ${{ steps.vars.outputs.url }}
